### ISSUE TITLE
How to transform JSDuck JSON to TernJS defs ?

### ISSUE THREAD

**Issue by fflorent** [angelozerr/tern.jsduck#2]
The home page explains how to get the JSDuck JSON data, but not how to convert it into TernJS defs structure. 

Thanks!
Florent

**Comment by angelozerr** [comment]
@fflorent see explanation at https://github.com/angelozerr/tern.jsduck#jsduck-extjson---tern-defs

Don't hesitate to create PR to improve https://github.com/angelozerr/tern.jsduck/blob/master/generator/JSDuckApi2TernDef.js thanks!
