### ISSUE TITLE
[ExtJS] Make completion work on class definition

### ISSUE THREAD

**Issue by fflorent** [angelozerr/tern.jsduck#5]
Based on the `extends` property, the completion would allow to autocomplete overridable properties and methods : 

``` javascript
Ext.define('MyBtn', {
  extend: 'Ext.button.Button', // with extend, we know what properties / config we can override
  te| // => autcompletes with 'text' and 'textAlign'
});
```

I plan to work on it next week (on tuesday and wednesday).

Florent

**Comment by angelozerr** [comment]
Very nice feature!
